language: php
php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

script:
 - vendor/bin/phpunit

before_script:
 - sudo apt-get -qq update > /dev/null
 - sudo apt-get -qq install fop > /dev/null
 - sudo apt-get -qq install libservlet2.4-java > /dev/null
 - phpenv rehash > /dev/null
 - composer selfupdate --quiet
 - composer install --dev --prefer-source
 - vendor/bin/phpunit
 - composer update --dev --prefer-source

notifications:
  email:
    - siad.ardroumli@idealo.de
