language: php
php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5

before_script:
 - sudo apt-get -qq update > /dev/null
 - sudo apt-get -qq install fop > /dev/null
 - sudo apt-get -qq install libservlet2.4-java > /dev/null
 - phpenv rehash > /dev/null
 - composer selfupdate --quiet
 - composer install --dev --prefer-source
 - composer update --dev --prefer-source
 - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls

notifications:
  email:
    - siad.ardroumli@idealo.de
